name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  cargo-fmt:
    name: cargo-fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get latest version of nightly Rust
      run: rustup update nightly
    - name: Check formatting with cargo fmt
      run: cargo +nightly fmt --all --verbose --check

  cargo-clippy:
    name: cargo-clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get latest version of stable Rust
      run: rustup update stable
    - name: Check clippy
      run: cargo clippy --all-features
